# Generated by Django 5.0.7 on 2024-08-02 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100, verbose_name='short description')),
                ('detailes', models.CharField(blank=True, default='', max_length=400, verbose_name='detailed description')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('travel_idea', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='travels.travelidea')),
            ],
        ),
    ]
