# Generated by Django 5.0.7 on 2024-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelidea',
            old_name='detailes',
            new_name='detailed',
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None),
        ),
    ]
